version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Europe/Warsaw"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      github-actions:
        patterns: ["*"]
